[PR-1] added Jupyter Notebook dependency for installation
hegelai/prompttools pull request #123
Opened 2024-03-17 06:00 UTC by jonatng

Jupyter Notebook installation is needed when installing promptTools

2024-03-17 06:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hegelai/prompttools?pullRequest=123) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hegelai/prompttools?pullRequest=123) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hegelai/prompttools?pullRequest=123) it.</sub>

2024-03-17 06:06 UTC, HashemAlsaket commented
Awesome catch

2024-03-20 03:57 UTC, jonatng commented
Hi @NivekT @steventkrawczyk 
Can I get some eyes on this PR please

2024-03-21 19:00 UTC, NivekT requested changes
Thanks for opening this PR! 

I think it should be added to the Quick Start section, possibly here:

```
cd prompttools && jupyter notebook examples/notebooks/OpenAIChatExperiment.ipynb
```

2024-03-25 18:21 UTC, NivekT requested changes
The change should still be in README but below
```bash
You can run a simple example of a `prompttools` locally with the following

```

2024-03-27 21:03 UTC, NivekT requested changes
`pip install notebook` should be in README not in a single Jupyter notebook

2024-03-29 04:16 UTC, jonatng commented
@NivekT  Added pip install notebook to README
Would you like to keep or remove pip install notebook from _prompttools/examples/notebooks/OpenAIChatExperiment.ipynb_

2024-03-29 22:57 UTC, NivekT commented on README.md
> +```
```suggestion
pip install notebook  # If jupyter notebook has not been installed
```

2024-03-29 22:57 UTC, NivekT commented on examples/notebooks/OpenAIChatExperiment.ipynb
> +    "# pip install notebook\n",
```suggestion
```

2024-03-29 22:58 UTC, NivekT commented on README.md
> +pip install notebook  # If jupyter notebook has not been installed
```suggestion
pip install notebook  # If jupyter notebook has not been installed
```
```

2024-03-29 22:58 UTC, merged