Added support for MongoDB Export of results for Instruction/Prompt Template
hegelai/prompttools pull request #55
Opened 2023-08-04 02:07 UTC by pramitbhatia25

Summary of changes:
Added export to_mongo_db option after generating results.
Added error handling in experiment.py to_mongo_db function.
Modified open_ai_chat_completion and open_ai_chat experiments, made them set completion functions only if DEBUG key doesn't exist.
Modified load_data function in data_loader.py to return a dict. If there's any error, it is displayed on the UI instead of the app crashing.
Added Anthropic / Google PALM / LlamaCpp Completion models in data loader so they don't error out when called.
(Support for these still needs work)

Important: Since I've modified data_loader.py / experiment.py, and the playground imports these from the prompttools package, we'll need to release a new version and update it. (I've tested the functions by using them directly in playground.py, they were working fine..)

2023-08-04 02:11 UTC, pramitbhatia25 commented
Hey guys. let me know if I should make any more modifications. I'm working on the to_mongo_db connection for Model Comparison, will need to modify the run_multiple function in data_loader.py file to get it working.

2023-08-04 20:36 UTC, steventkrawczyk commented on prompttools/playground/data_loader.py
> +    data_loader_response = {'error': []}
For error handling, why not just raise an error? Streamlit will show that to the user

2023-08-04 20:38 UTC, steventkrawczyk commented on requirements.txt
> +pymongo
Since we guard the import, we don't need to install here.

2023-08-04 20:38 UTC, steventkrawczyk commented
This is a great start! 
* You'll need to rebase on the latest changes from today, we're updating the UI a bit
* Could you attach a few screenshots to show how the UI will look with these changes?

2023-08-04 20:40 UTC, steventkrawczyk requested changes
Looks good so far! Left a few comments

2023-08-05 18:46 UTC, steventkrawczyk commented
One more idea here: can we use streamlit's connectors for mongodb? 

https://docs.streamlit.io/knowledge-base/tutorials/databases/mongodb

2023-08-06 15:13 UTC, closed without merging

2023-08-06 15:16 UTC, pramitbhatia25 commented
Gotcha, I'll make these changes, will open another PR when I'm done. Thanks!